### ISSUE TITLE
Add GEO242 for lecture recording schedule

### ISSUE THREAD

**Issue by JanKoppe** [fs-geofs/geofsdisplay#12]
Hi,

in the coming winter term we also provide lecture capture via eLectures in room GEO242. You might want to add the schedule for that room to your display as well?

**Comment by christophfriedrich** [comment]
Closing as displaying lecture capture information has been discontinued altogether in 750a3dcdab08adfb3677c9c7a6234b2670cbac9b (see the extended message of that commit for the reasons)
