### ISSUE TITLE
Data source for Mensa Speisepläne 

### ISSUE THREAD

**Issue by chk1** [fs-geofs/geofsdisplay#14]
Hi,

The XMLs from Studierendenwerk are no longer being updated. 

Here's an alternative if needed (a parser for my-mensa): https://github.com/chk1/stw2openmensa/issues/15#issuecomment-728103161

**Comment by christophfriedrich** [comment]
Yeah, I noticed that myself a while ago, but (considering the amount of work to write a full parser) so far I didn't bother enough to fix it :sweat_smile: But this looks awesome! I'll try to implement it over the weekend. Thanks a lot for remembering us and providing the link!

**Comment by christophfriedrich** [comment]
Wow, that was a breeze! Barely any changes needed. It's deployed now, so happy mensing :D
