### ISSUE TITLE
Mensaplan broken

### ISSUE THREAD

**Issue by christophfriedrich** [fs-geofs/geofsdisplay#2]
Since the Studentenwerk changed their Mensaplan publishing method, the mensa parser is broken. There [seems to be an API](https://fb4-app-blog.uni-muenster.de/2016/07/12/die-neue-mensa-api/) for the new system which already works in the WiWi app. We should wait for the outcome of [this conversation](https://github.com/ifgi-webteam/mensaparser/issues/4) before attempting to fix anything ourselves.

**Comment by christophfriedrich** [comment]
I wrote to the Studentenwerk from our fsgi mail, they forwarded that to infomax.de who manages the plans for them and they gave us the information that the new publishing method is via XMLs that are located at http://speiseplan.stw-muenster.de/mensa_am_ring.xml I implemented the new method into mensaplaene.php with bc37750

**Comment by noerw** [comment]
The filter for `Aktionsstand (WOK)` does not work.
![photo465669404184651972](https://cloud.githubusercontent.com/assets/7880552/20264946/684e3022-aa6e-11e6-9d98-b90bd438efcc.jpg)

Can we just limit the output to 4 items? It takes to much space.

**Comment by christophfriedrich** [comment]
Yes, the filter does work, it's supposed to only remove the "Heute am " to make it somewhat shorter.

I thought about limiting the items too, but couldn't decide which ones to keep and which not. If we reduce it, I'd say keep only Menu 1-3 and nothing else. To start with, I'd certainly remove the Dessertbuffet. 

Alternatively, use a smaller font size? (Or redesign the whole thing?)

**Comment by noerw** [comment]
should be working now
