### ISSUE TITLE
PDF-Viewer

### ISSUE THREAD

**Issue by sNiklasch** [fs-geofs/geofsdisplay#3]
Falls es weiterhin noch so gemacht wird...
Um nicht immer den "Umweg" über PNG/JPEG etc. gehen zu müssen, könnte man einen PDF-Viewer (z.B. https://github.com/mozilla/pdf.js ) ergänzen. Natürlich müsste die Performance auf dem RPI geprüft werden...

**Comment by noerw** [comment]
PDFs sind nun unterstuetzt, und werden beim upload serverseitig direkt zu grafiken konvertiert
https://github.com/fs-geofs/geofsdisplay/commit/cb9ea003f8b8d1d0ffe50fdb3837579f50701a91
